# KNN
knn intro: https://www.cnblogs.com/fengfenggirl/archive/2013/05/27/knn.html

In [1]:
import numpy as np
import pandas as pd
from pandas import concat
final_data = pd.read_csv("processed_data.csv")
unsplited_data = final_data.iloc[:, [1, 2, 3, 0]]
train_data = final_data.iloc[:49046, [1, 2, 3, 0]]
test_data = concat([final_data.iloc[0:0, [1, 2 , 3, 0]], final_data.iloc[49047:, [1 , 2, 3, 0]]])
print(train_data[:10])

              userid     entityName               type body
0    878293195646842       Bio Cafe  point_of_interest    🌮
1    878293195646842       Bio Cafe      establishment    🌮
2    878293195646842       Bio Cafe  point_of_interest    🌮
3    878293195646842       Bio Cafe      establishment    🌮
4  10212886863311893  Lao sze chuan  point_of_interest    🐔
5  10212886863311893  Lao sze chuan      establishment    🐔
6  10212886863311893  Lao sze chuan  point_of_interest    🍗
7  10212886863311893  Lao sze chuan      establishment    🍗
8  10212886863311893  Lao sze chuan  point_of_interest    😍
9  10212886863311893  Lao sze chuan      establishment    😍


In [2]:
unsplited_data

userid  \
0                   878293195646842   
1                   878293195646842   
2                   878293195646842   
3                   878293195646842   
4                 10212886863311893   
5                 10212886863311893   
6                 10212886863311893   
7                 10212886863311893   
8                 10212886863311893   
9                 10212886863311893   
10                10212886863311893   
11                10212886863311893   
12                10212886863311893   
13                10212886863311893   
14                10212886863311893   
15                10212886863311893   
16                  878293195646842   
17                  878293195646842   
18                  878293195646842   
19                  878293195646842   
20                  878293195646842   
21                  878293195646842   
22                  878293195646842   
23                  878293195646842   
24                10212886863311893   
25                10212886863311893   
26                10212886863311893   
27                10212886863311893   
28                10212886863311893   
29                10212886863311893   
...                             ...   
73538         106173579224565293482   
73539         106173579224565293482   
73540         106173579224565293482   
73541         106173579224565293482   
73542  v5peK8F0fWW8v9Bs7OlRGswpUxH3   
73543  v5peK8F0fWW8v9Bs7OlRGswpUxH3   
73544  v5peK8F0fWW8v9Bs7OlRGswpUxH3   
73545  v5peK8F0fWW8v9Bs7OlRGswpUxH3   
73546  v5peK8F0fWW8v9Bs7OlRGswpUxH3   
73547  v5peK8F0fWW8v9Bs7OlRGswpUxH3   
73548  v5peK8F0fWW8v9Bs7OlRGswpUxH3   
73549  v5peK8F0fWW8v9Bs7OlRGswpUxH3   
73550             10155200088205955   
73551             10155200088205955   
73552             10155200088205955   
73553             10155200088205955   
73554             10155200088205955   
73555             10155200088205955   
73556             10155200088205955   
73557             10155200088205955   
73558             10155200088205955   
73559             10155200088205955   
73560  oCO1XnwTPub9pAXnMwOpAwQq65m1   
73561  oCO1XnwTPub9pAXnMwOpAwQq65m1   
73562  oCO1XnwTPub9pAXnMwOpAwQq65m1   
73563  oCO1XnwTPub9pAXnMwOpAwQq65m1   
73564  oCO1XnwTPub9pAXnMwOpAwQq65m1   
73565  oCO1XnwTPub9pAXnMwOpAwQq65m1   
73566  oCO1XnwTPub9pAXnMwOpAwQq65m1   
73567  oCO1XnwTPub9pAXnMwOpAwQq65m1   

                                         entityName               type body  
0                                          Bio Cafe  point_of_interest    🌮  
1                                          Bio Cafe      establishment    🌮  
2                                          Bio Cafe  point_of_interest    🌮  
3                                          Bio Cafe      establishment    🌮  
4                                     Lao sze chuan  point_of_interest    🐔  
5                                     Lao sze chuan      establishment    🐔  
6                                     Lao sze chuan  point_of_interest    🍗  
7                                     Lao sze chuan      establishment    🍗  
8                                     Lao sze chuan  point_of_interest    😍  
9                                     Lao sze chuan      establishment    😍  
10                                          Jip Bap  point_of_interest    😍  
11                                          Jip Bap      establishment    😍  
12                                          Jip Bap  point_of_interest    🍲  
13                                          Jip Bap      establishment    🍲  
14                                          Jip Bap  point_of_interest    🍚  
15                                          Jip Bap      establishment    🍚  
16               Butterfly Sushi Bar & Thai Cuisine  point_of_interest    🇹  
17               Butterfly Sushi Bar & Thai Cuisine      establishment    🇹  
18               Butterfly Sushi Bar & Thai Cuisine  point_of_interest    🇭  
19               Butterfly Sushi Bar & Thai Cuisin

In [3]:
data = unsplited_data[1:].values
np.random.shuffle(data)

In [4]:
data[:10]

array([['10212391291791338', 'University of Illinois Campus Recreation',
        'point_of_interest', '♂'],
       ['106173579224565293482', "O'Hare International Airport",
        'establishment', '👩'],
       ['115361705896308', 'MOMOYA', 'point_of_interest', '👨'],
       ['IJ0ppMi7HtNFuc7Ar4E8aog2urq2',
        'Allô! Mon Coco - Plateau Mont-Royal', 'establishment', '🍳'],
       ['aly2Ytiq6Je34uw9KjbN6XFAEqs1', 'Sushi Kame', 'establishment',
        '😋'],
       ['10212391291791338', 'University of Illinois Campus Recreation',
        'point_of_interest', '🏃'],
       ['105856798281199967470', "O'Hare International Airport",
        'establishment', '\U000e007f'],
       ['Ybwj1wTN0rVKBHTbr4YbiK0JMyc2', 'Hôtel Ritz Paris',
        'establishment', '⃣'],
       ['878293195646842', 'Black Dog Smoke & Ale House',
        'establishment', '🍖'],
       ['108032751776815363988', 'NoMad Bar', 'point_of_interest', '🤑']],
      dtype=object)

In [5]:
import hashlib
d1 = {}
def md5_1(s): 
    h = int(hashlib.md5(s.encode()).hexdigest(),16) / 1e29
    d1[h] = s  
    return h
d2 = {}
def md5_2(s): 
    h = int(hashlib.md5(s.encode()).hexdigest(),16) / 1e28
    d2[h] = s  
    return h 

In [6]:
# https://www.bilibili.com/video/av64111297?p=46  
# in the video: (mutiply x => 2 outputs (0 or 1)) => supervised learning (46-49)
# in this problem: (mutiply x => mutiply y(unknown)) => unsupervised learning (156)
# KNN, Decision trees, SVM => https://www.geeksforgeeks.org/multiclass-classification-using-scikit-learn/
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression
a= data[::, :-1].tolist()
b= data[::, -1:].tolist()
# print(a[:3],'\n',len(a),'\n',type(a),'\n')
# print(b[:3],'\n',len(b),'\n',type(b),'\n')
a_ = []
for l in a:
    t = []
    for i in range(3): t.append(md5_1(l[i]))
    a_.append(t)
a = a_
b = [md5_2(item) for l in b for item in l]
# print(d1[15205963056818863091954712931819521019])
# print(d1[99396071082847217712602878136621166525])
# print(d2[140598361932073884279234491729198167766])
# data/1e28 => handle overflow error
x = np.asarray(a,dtype ='float64').reshape(-1,3)
y = np.asarray(b,dtype ='int64')
print(x[:10],'\n\n', y[:10])

[[1.57803717e+09 1.93728040e+09 7.49855338e+08]
 [1.73574154e+08 1.43329909e+09 3.24878142e+09]
 [2.68719694e+09 9.78779910e+08 7.49855338e+08]
 [3.48076721e+08 2.25792587e+09 3.24878142e+09]
 [1.38591906e+09 1.42885503e+09 3.24878142e+09]
 [1.57803717e+09 1.93728040e+09 7.49855338e+08]
 [8.54110008e+08 1.43329909e+09 3.24878142e+09]
 [1.12594923e+09 6.97379788e+08 3.24878142e+09]
 [1.52059631e+08 2.55302673e+09 3.24878142e+09]
 [9.45613472e+08 1.06525716e+09 7.49855338e+08]] 

 [ 2288664447 21348747340 22816766964   360454618 21354989949 21263262544
 21172942018  4596275288  3057886082 11831439227]


In [7]:
# # importing necessary libraries 
# from sklearn import datasets 
# from sklearn.metrics import confusion_matrix 
# from sklearn.model_selection import train_test_split 
  
# # loading the iris dataset 
# iris = datasets.load_iris() 
  
# # X -> features, y -> label 
# X = iris.data 
# Y = iris.target 
  
# # dividing X, y into train and test data 
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 0) 
  
# # training a DescisionTreeClassifier 
# from sklearn.tree import DecisionTreeClassifier 
# dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, Y_train) 
# dtree_predictions = dtree_model.predict(X_test) 
  
# # creating a confusion matrix 
# cm1 = confusion_matrix(Y_test, dtree_predictions) 

In [8]:
# print(X.shape,Y.shape, type(X[0][0]), type(Y[0]))
# print(X[:5],Y[:5])
# print(Y_test, dtree_predictions)

In [9]:
# print(38/150)
# print(Y_test.shape, dtree_predictions.shape)
# cm1

In [10]:
# print(x.shape,y.shape, type(x[0][0]), type(y[0]))

In [11]:
# # dividing X, y into train and test data 
# x1_train, x1_test, y1_train, y1_test = train_test_split(x, y, random_state = 0) 
  
# # training a DescisionTreeClassifier 
# from sklearn.tree import DecisionTreeClassifier 
# dtree_model1 = DecisionTreeClassifier(max_depth = 2).fit(x1_train, y1_train) 
# dtree_predictions1 = dtree_model1.predict(x1_test) 
  
# # creating a confusion matrix 
# cm2 = confusion_matrix(y1_test, dtree_predictions1) 

In [12]:
# print(cm2.shape)
# cm2

In [13]:
# print(y1_test.shape, dtree_predictions1.shape)
# l2 = cm2.tolist()
# for i in range(len(l2)):
#     for j in range(len(l2[i])):
#          if l2[i][j]:
#             print( i,j, l2[i][j] )

In [14]:
# # importing necessary libraries 
# from sklearn import datasets 
# from sklearn.metrics import confusion_matrix 
# from sklearn.model_selection import train_test_split 
  
# # loading the iris dataset 
# iris = datasets.load_iris() 
  
# # X -> features, y -> label 
# X1 = iris.data 
# Y1 = iris.target 
  
# # dividing X, y into train and test data 
# X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y1, random_state = 0) 
  
# # training a linear SVM classifier 
# from sklearn.svm import SVC 
# svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X1_train, Y1_train) 
# svm_predictions = svm_model_linear.predict(X1_test) 
  
# # model accuracy for X_test   
# accuracy = svm_model_linear.score(X1_test, Y1_test) 
  
# # creating a confusion matrix 
# cm3 = confusion_matrix(Y1_test, svm_predictions) 

In [15]:
# print(X1.shape,Y1.shape, type(X1[0][0]), type(Y1[0]))

In [16]:
# print(Y1_test.shape, svm_predictions.shape)
# cm3

In [17]:
# # importing necessary libraries 
# from sklearn import datasets 
# from sklearn.metrics import confusion_matrix 
# from sklearn.model_selection import train_test_split 
  
# # dividing X, y into train and test data 
# x2_train, x2_test, y2_train, y2_test = train_test_split(x, y, random_state = 0) 
  
# # training a linear SVM classifier 
# from sklearn.svm import SVC 
# svm_model_linear = SVC(kernel = 'linear', C = 1).fit(x2_train, y2_train) 
# svm_predictions = svm_model_linear.predict(x2_test) 
  
# # model accuracy for X_test   
# accuracy = svm_model_linear.score(x2_test, y2_test) 
  
# # creating a confusion matrix 
# cm4 = confusion_matrix(y2_test, svm_predictions) 

In [18]:
# print(x.shape,y.shape, type(x[0][0]), type(y[0]))

In [19]:
# print(y2_test.shape, svm_predictions.shape)
# cm4
# l4 = cm4.tolist()
# for i in range(len(l4)):
#     for j in range(len(l4[i])):
#          if l4[i][j]:
#             print( i,j, l4[i][j] )

In [38]:
# concatenate: http://lagrange.univ-lyon1.fr/docs/numpy/1.11.0/reference/generated/numpy.concatenate.html
from sklearn import datasets 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier 
from matplotlib import pyplot as plt
import copy
accuracy = 0
k = 0
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 0)
x_ = copy.deepcopy(x_train)
y_ = copy.deepcopy(y_train)
import time
timeout = time.time() + 40   # 40s from now
while accuracy < 1:
    k += 1000
#   M2 => improve the accuracy into ~ stable 95 - 99%
#   x3_train, x3_test, y3_train, y3_test = train_test_split(x_[:k], y_[:k], random_state = 0)
#   knn = KNeighborsClassifier(n_neighbors = 1).fit(x3_train, y3_train) # change from 7 to 1
    knn = KNeighborsClassifier(n_neighbors = 1).fit(x_[:k], y_[:k]) # change from 7 to 1
#   M1 => the accuracy into ~ unstable 80 - 99 %
    accuracy = knn.score(x_[:k], y_[:k]) 
    print(accuracy)
    knn_predictions = knn.predict(x_[:k])
    y_[:len(knn_predictions)] = knn_predictions
    if k + 1000 >= len(x_):
        x_ = np.concatenate((x_[k:], x_[:k]), axis=0) 
        y_ = np.concatenate((y_[k:], y_[:k]), axis=0) 
        k = 1000
    if time.time() > timeout: break

0.951
0.9275
0.9353333333333333
0.934
0.9308
0.9323333333333333
0.9271428571428572
0.9325
0.9385555555555556
0.9391
0.9451818181818182
0.9414166666666667
0.9416923076923077
0.9461428571428572
0.9484666666666667
0.9491875
0.9471764705882353
0.9521666666666667
0.9542105263157895
0.95445
0.9512380952380952
0.9542727272727273
0.9586086956521739
0.957375
0.9596
0.961
0.9605555555555556
0.9616428571428571
0.9621379310344828
0.9631
0.9601612903225807
0.96490625
0.966939393939394
0.9645588235294118
0.967
0.9671666666666666
0.9635945945945946
0.9669473684210527
0.9666153846153847
0.968675
0.9672926829268292
0.9678571428571429
0.9717674418604652
0.9702954545454545
0.9711777777777778
0.9735869565217391
0.970404255319149
0.9731875
0.9718979591836735
0.97636
0.9745490196078431
0.9724038461538461
0.9741509433962264
0.9740925925925926
0.9748


In [40]:
# creating a confusion matrix 
knn_predictions = knn.predict(x_)  
cm5 = confusion_matrix(y_, knn_predictions) 

In [41]:
print(y_, knn_predictions)

[26662516422 33921508374 26950051886 ... 26642082366  2178454635
  9322932166] [31184752339  7429030373 14355335374 ... 26642082366  2178454635
  9322932166]


In [42]:
print(x.shape,y.shape, type(x[0][0]), type(y[0]))
print(y_.shape, knn_predictions.shape)
# print(cm5)
l5 = cm5.tolist()
c5 = 0
for i in range(len(l5)):
    mx =0 
    for j in range(len(l5[i])):
        mx = max(l5[i][j],mx)
#         if l5[i][j]:
#             print( i,j, l5[i][j] )
#         if l5[i][j] and i == j:
#             cnt += 1
#             print( i,j, l5[i][j] )
    if l5[i][i] == mx:
        c5 += 1
#         print(i, l5[i][i], mx)

(73567, 3) (73567,) <class 'numpy.float64'> <class 'numpy.int64'>
(55175,) (55175,)


In [43]:
print(c5, len(l5))
print('accuracy = ', c5/len(l5))

889 894
accuracy =  0.9944071588366891


In [44]:
# accuracy on X_test 
accuracy1 = knn.score(x, y) 
print('original score = ', accuracy1)
accuracy2 = knn.score(x_train, y_train) 
print('train score =', accuracy2)
accuracy3 = knn.score(x_, y_) 
print('copy training phase score = ', accuracy3)

original score =  0.20986311797409166
train score = 0.2625283189850476
copy training phase score =  0.997009515178976


In [45]:
from sklearn import datasets 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 

# dividing X, y into train and test data 
x4_train, x4_test, y4_train, y4_test = train_test_split(x, y, random_state = 0) 
  
# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(x4_train, y4_train) 
gnb_predictions = gnb.predict(x4_test) 
  
# accuracy on X_test 
# accuracy = gnb.score(x4_test, y4_test) 
# print(accuracy) 
  
# creating a confusion matrix 
cm6 = confusion_matrix(y4_test, gnb_predictions) 

In [46]:
print(x.shape,y.shape, type(x[0][0]), type(y[0]))
print(y4_test.shape, gnb_predictions.shape)
# print(cm6)
l6 = cm6.tolist()
c6 = 0
for i in range(len(l6)):
    mx = 0
    for j in range(len(l6[i])):
        mx = max(mx, l6[i][j])
#          if l6[i][j]:
#             print( i,j, l6[i][j] )
#         if l6[i][j] and i == j:
#             print( i,j, l6[i][j] )
    if l6[i][i] == mx:
        c6 += 1
#         print(i, l6[i][i])

(73567, 3) (73567,) <class 'numpy.float64'> <class 'numpy.int64'>
(18392,) (18392,)


In [47]:
print(c6)
print('accuracy = ', c6/len(l6))

71
accuracy =  0.06807286673058485
